'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Lingo.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property greenball() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("greenball", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property greenrr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("greenrr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hack() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hack", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hack2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hack2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Lingo_Crown_No_Text() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lingo_Crown_No_Text", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lingobg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lingobg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lingobg1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lingobg1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lingobg10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lingobg10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lingobg11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lingobg11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lingobg2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lingobg2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lingobg3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lingobg3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lingobg4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lingobg4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lingobg5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lingobg5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lingobg6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lingobg6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lingobg7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lingobg7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lingobg8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lingobg8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lingobg9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lingobg9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AAHED
        '''AALII
        '''AARGH
        '''AARTI
        '''ABACA
        '''ABACI
        '''ABACK
        '''ABACS
        '''ABAFT
        '''ABAKA
        '''ABAMP
        '''ABAND
        '''ABASE
        '''ABASH
        '''ABASK
        '''ABATE
        '''ABAYA
        '''ABBAS
        '''ABBED
        '''ABBES
        '''ABBEY
        '''ABBOT
        '''ABCEE
        '''ABEAM
        '''ABEAR
        '''ABELE
        '''ABERS
        '''ABETS
        '''ABHOR
        '''ABIDE
        '''ABIES
        '''ABLED
        '''ABLER
        '''ABLES
        '''ABLET
        '''ABLOW
        '''ABMHO
        '''ABODE
        '''ABOHM
        '''ABOIL
        '''ABOMA
        '''ABOON
        '''ABORD
        '''ABORE
        '''ABORT
        '''ABOUT
        '''ABOVE
        '''ABRAM
        '''ABRAY
        '''ABRIM
        '''ABRIN
        '''ABRIS
        '''ABSEY
        '''ABSIT
        '''ABUNA
        '''ABUNE
        '''ABUSE
        '''ABUTS
        '''ABUZZ
        '''ABYES
        '''ABYSM
        '''ABYSS
        '''ACAIS
        '''ACARI
        '''ACCAS
        '''ACCOY
        '''ACERB
        '''ACERS
        '''ACETA
        '''ACHAR
        '''ACHED
        '''ACHES
        '''ACHOO
        '''A [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property LingoWords() As String
            Get
                Return ResourceManager.GetString("LingoWords", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property playerBG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("playerBG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property playerBG2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("playerBG2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property playerBG3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("playerBG3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property playerBG4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("playerBG4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property playerBGgreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("playerBGgreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property playerBGred() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("playerBGred", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redball() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redball", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redx() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redx", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property yellowball() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("yellowball", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
